config/routes.rb
Rails.application.routes.draw do
  resources :items

  resources :menus

  devise_for :admins
  root "pages#home"
  get "about" => "pages#about"
  get "menu" => "pages#menu"
  get "gallery" => "pages#gallery"

  devise_scope :admin do get '/admins/sign_out' => 'devise/sessions#destroy' end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @items = Item.all
    @menus = Menu.all

  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to("/menu")
  end

  def update
    @item.update(item_params)
    redirect_to("/menu")
  end

  def destroy
    @item.destroy
    redirect_to(:back)
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:items, :description, :cost, :category)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @menus = Menu.all
    @items = Item.all
    respond_with(@menus)
  end

  def menu
    @menu = Menu.all
    @items = Item.all
  end

  def show
    respond_with(@menu)
  end

  def new
    @menu = Menu.new
    respond_with(@menu)
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.save
    redirect_to("/menu")
  end

  def update
    @menu.update(menu_params)
    redirect_to("/menu")
  end

  def destroy
    @menu.destroy
    redirect_to(:back)
  end

  private
    def set_menu
      @menu = Menu.find(params[:id])
    end

    def menu_params
      params.require(:menu).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def menu
    @menus = Menu.all
    @items = Item.all
    @item = Item.new
    @menu = Menu.new
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :items %><br>
    <%= f.text_field :items %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary outline">Create</button>
  </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', '/menu' %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Items</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.items %></td>
        <td><%= item.description %></td>
        <td><%= item.cost %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>


<%= render 'form' %>

<%= link_to 'Back', '/menu' %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Items:</strong>
  <%= @item.items %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @item.cost %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', '/menu' %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href= "/">Kamman</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Menu", '/menu' %></li>
      <li><%= link_to "Gallery", gallery_path %></li>
      <li><%= link_to "About", about_path %></li> 
    </ul>


      <%if admin_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Log out", destroy_admin_session_path %></li>
      </ul>
      <% end %>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kamman</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/header' %>
  <% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <%end%>
  <%= yield %>
</body>
</html>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>


  <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary outline">Create</button>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', '/menu' %>

app/views/menus/index.html.erb
<h1>Menu</h1>

<table>
  <thead>
    <tr>
      <th>Menu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Items</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.items %></td>
        <td><%= item.description %></td>
        <td><%= item.cost %></td>
        <td><%= item.category %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to 'New Menu', new_menu_path %>
<%= link_to 'New Item', new_item_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', '/menu' %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', '/menu' %>

app/views/pages/_itemModal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-default btn-lg sharp" data-toggle="modal" data-target="#myItems">
  New Item
</button>

<!-- Modal -->
<div class="modal fade" id="myItems" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Item</h4>
      </div>
      <div class="modal-body">
        <%= render :partial => "items/form", :locals => {:item=> Item.new} %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_menuModal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-default btn-lg sharp  " data-toggle="modal" data-target="#myModal">
  New Menu
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Menu</h4>
      </div>
      <div class="modal-body">
        <%= render :partial => "menus/form", :locals => {:menu=> Menu.new} %>
      </div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p></p>

app/views/pages/gallery.html.erb
<h1> Gallery </h1>

app/views/pages/home.html.erb
<h1>Kam Man </h1>
<p>Chinese Fast Food</p>

<p>
 <%= link_to "Log in", new_admin_session_path, class: "btn btn-default btn-lg sharp" %>
 <%= link_to "Sign up", new_admin_registration_path, class: "btn btn-primary btn-lg sharp outline" %>
 </p>

app/views/pages/menu.html.erb


<%= render "menuModal"%>
<%= render "itemModal"%>


<div class = "spacing">
	<table class=" table-condensed">
		<% @menus.each do |menu| %>
		  <thead>
				<tr>
			 	 <th><font size="4"><%= menu.name %></font></th>
			 	 <th></th>
			 	 <th><%= link_to 'Edit', edit_menu_path(menu)%></th>
			 	 <th><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></th>
			 	<th colspan="1"></th>
				</tr>
		 	</thead>
		 	<tbody>
				<% @items.each do |item| %>
					<tr>
						<%if menu.name == item.category %>
							<td><%= item.items %></td>
							<td>$<%= item.cost %></td>
							<td><%= link_to 'Edit', edit_item_path(item) %></td>
							<td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  		<% end %>
					<% end %>
				</tr>
			</tbody>
		<%end %>
	</table>
</div>